name:               "Areum"
description:        "Software engineer"

url:                ""
author:             "hanareum95"
email:              "areum9502@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "areum9502@gmail.com"
github:             "hanareum95"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "armful"

background:         "http://apple.wallpapersfine.com/wallpapers/preview/750x1334/w-17181.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Etc"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate